---
- hosts: all
  gather_facts: false
  connection: local

  tasks:

    - name: Push RPM Telegraph Package on Arista
      ansible.builtin.copy:
        src: ./telegraf-1.2.0.i386.rpm
        dest: /mnt/flash/telegraf-1.2.0.i386.rpm
        owner: root
        group: root
        mode: u+rwx
