---
- hosts: all
  ansible_connection: ansible.netcommon.network_cli
  gather_facts: false
  collections:
    - ansible.netcommon

  tasks:

    - name: Push RPM Telegraph Package on Arista
      ansible.netcommon.net_put:
        src: ./telegraf.rpm
        dest: /mnt/flash
        protocol: scp
