---
- hosts: all
  gather_facts: false
  connection: local
  collections:
    - ansible.netcommon
    - arista.eos

  tasks:

    - name: Push RPM Telegraph Package on Arista
      vars:
        ansible_connection: network_cli
      ansible.netcommon.net_put:
        src: ./telegraf.rpm
        dest: /mnt/flash
        protocol: scp

    - name: Push Telegraf Install Script
      vars:
        ansible_connection: network_cli
      ansible.netcommon.net_put:
        src: ./installtelegraf.sh
        dest: /mnt/flash
        protocol: scp

    - name: Install Telegraf RPM
      arista.eos.eos_command:
        commands:
        - show version
